version: '3.8'

services:
  app-solar-frontend:
    build: .
    container_name: vichen-app-solar
    restart: unless-stopped
    ports:
      # Formato: "PUERTO_EXTERNO:PUERTO_INTERNO"
      # Como tienes otros servicios en tu VPS, he puesto el 8080.
      # Si el 8080 está ocupado, cámbialo por el que prefieras (ej. "8085:80" o "3000:80").
      - "8080:80"
    environment:
      - TZ=Europe/Madrid
